services:
  db:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - scout-postgres-data:/var/lib/postgresql/data
    hostname: postgres
volumes:
  scout-postgres-data:
